language: php

php: 7.4

branches:
    only:
        - master

install:
    - composer install

scripts:
    # tweet a new post - depends on content being published on server, so must be AFTER deploy
    # get tokens to Travis ENV: https://travis-ci.com/TomasVotruba/tomasvotruba.com/settings
    # from here: https://developer.twitter.com/en/apps/14147884
    - bin/console tweet --ansi
