imports:
    - { resource: '../vendor/symplify/symfony-static-dumper/config/config.php' }
    - { resource: '_data/*' }
    - { resource: '_data/generated/*' }

parameters:
    site_url: "%env(SITE_URL)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

        bind:
            $projectDir: "%kernel.project_dir%"

    TomasVotruba\Website\:
        resource: '../src/*'
        exclude:
            - '../src/HttpKernel/*'
            # testing of post code
            - '../src/Posts/*'
