name: Refresh Framework Stats

on:
    push: null

    # to try it out
    schedule:
        # every 1st day in month at 12:00 https://crontab.guru/#00_12_1_*_*
        -   cron: "00 12 1 * *"

jobs:
    refresh_framework_stats:
        runs-on: ubuntu-latest

        steps:
            -
                name: Get current Month
                # see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#example-4
                run: echo "CURRENT_MONTH=$(echo date::$('%Y-%m'))" >> $GITHUB_ENV

            -
                run: echo $CURRENT_MONTH

            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            -
                name: Generate Framework Stats for Last Month
                run: bin/console generate-stats --ansi



            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    commit-message: "update framework stats ${CURRENT_MONTH}"
                    branch: ci-generated-framework-stats
                    base: 'master'
                    title: "Automated Update of Framework Stats for ${CURRENT_MONTH}"
                    delete-branch: true
